.TH ALCC 1
.SH NAME
alcc \- create ed2k link in command-line
.SH SYNOPSIS
.B alcc
.SH "DESCRIPTION"
.B alcc
is a link creator for aMule.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH "SEE ALSO"
You can see the Changelog file and README.Debian in the /usr/share/doc directory
.SH AUTHOR
aMule was written by Stephane Colin <bigbog@tiscali.fr>
This manpage was written by Julien Delange for Debian <julien AT gunnm DOT org>



