.TH AMULECMD 1
.SH NAME
amulecmd \- Text-based program to control amule
.SH SYNOPSIS
.B amulecmd
.SH "DESCRIPTION"
.B amulecmd
is a texte based client to control amule. Useful help can
be obtained when you launch the program.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH "SEE ALSO"
You can see the Changelog file and README.Debian in the /usr/share/doc directory
.SH AUTHOR
aMule was written by Stephane Colin <bigbog@tiscali.fr>
This manpage was written by Julien Delange for Debian <julien AT gunnm DOT org>



