.TH AMULECMDDLG 1
.SH NAME
amulecmdDLG \- Controle de aMule a travers une interface GTK
.SH SYNOPSIS
.B amulecmdDLG
.SH "DESCRIPTION"
.B amulecmdDLG
Vous permet de faire les mêmes choses que amulecmd, mis à part que ce programme 
est en GTK+. Il est donc doté d'une interface graphique.
.PP
Cette page de manuel a été écrite pour Debian, car le logiciel original n'en avait pas.

.SH "VOIR AUSSI"
Vous pouvez consultez les fichiers relatifs à ce programme dans le répertoire /usr/share/doc/amule/

.SH "AUTEUR"
aMule a été écrit par Stéphane Colin <bigbog AT tiscali DOT fr>, ainsi que de nombreux contributeurs.
Cette page de manuel a été écrite par Julien Delange <julien AT gunnm DOT org>. Merci de me contacter pour tout problème.



