.TH AMULE 1
.SH NAME
amule \- aNother Peer to Peer client
.SH SYNOPSIS
.B amule
.SH "DESCRIPTION"
.B amule
est un client Peer to Peer qui permet de se connecter au réseau eDonkey (eMule, ...)
.PP
Cette page de manuel a été écrite pour Debian, car le logiciel original n'en avait pas.

.SH "VOIR AUSSI"
Vous pouvez consultez les fichiers relatifs à ce programme dans le répertoire /usr/share/doc/amule/

.SH "AUTEUR"
aMule a été écrit par Stéphane Colin <bigbog AT tiscali DOT fr>, ainsi que de nombreux contributeurs.
Cette page de manuel a été écrite par Julien Delange <julien AT gunnm DOT org>. Merci de me contacter pour tout problème.



