.TH AMULECMD 1
.SH NAME
amulecmd \- Control du programme amule à travers une interface en mode texte.
.SH SYNOPSIS
.B amulecmd
.SH "DESCRIPTION"
.B amulecmd
est un programme qui vous permet de commander le logiciel amule en ligne de commande.
.PP
Cette page de manuel a été écrite pour Debian, car le logiciel original n'en avait pas.

.SH "VOIR AUSSI"
Vous pouvez consultez les fichiers relatifs à ce programme dans le répertoire /usr/share/doc/amule/

.SH "AUTEUR"
aMule a été écrit par Stéphane Colin <bigbog AT tiscali DOT fr>, ainsi que de nombreux contributeurs.
Cette page de manuel a été écrite par Julien Delange <julien AT gunnm DOT org>. Merci de me contacter pour tout problème.



