.TH AMULE 1
.SH NAME
amuled \- aMule daemon
.SH SYNOPSIS
.B amuled
.SH "DESCRIPTION"
.B amuled
is a small daemon which allows you to run aMule without GUI.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH "SEE ALSO"
You can see the Changelog file and README.Debian in the /usr/share/doc directory
.SH AUTHOR
aMule was written by Stephane Colin <bigbog@tiscali.fr>
This manpage was written by Julien Delange for Debian <julien AT gunnm DOT org>



