.TH AMULEGUI 1
.SH NAME
amulegui \- aMule control program with GUI
.SH SYNOPSIS
.B amulegui
.SH "DESCRIPTION"
.B amulegui
is a client program, and can be connected on amule server. You
can manage your amule program with it. It provides the same functionality
as amule, except than the core works on another computer.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH "SEE ALSO"
You can see the Changelog file and README.Debian in the /usr/share/doc directory
.SH AUTHOR
aMule was written by Stephane Colin <bigbog@tiscali.fr>
This manpage was written by Julien Delange for Debian <julien AT gunnm DOT org>



