.TH ED2K.AMULE 1
.SH NAME
ed2k \- binaire utilisé par le programme amule
.SH SYNOPSIS
.B ed2k.amule
.SH "DESCRIPTION"
.B ed2k
est un binaire utilisé par le programme amule. Il sert à passer les URL de type ed2k:// dans le programme amule.
.PP
Cette page de manuel a été écrite pour Debian, car le logiciel original n'en avait pas.

.SH "AUTEUR"
ed2k a été écrit par la amule team (site : http://amule.sourceforge.net)
Cette page de manuel a été écrite par Julien Delange <julien AT gunnm DOT org>. Merci de me contacter pour tout problème.



