.TH ED2K 1
.SH NAME
ed2k \- wrapper for {x|a}Mule
.SH SYNOPSIS
.B ed2k
.SH "DESCRIPTION"
.B ed2k
is a binary used by to invoke ed2k.amule or ed2k.xmule. Its a specific wrapper for Debian.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH AUTHOR
ed2k and this manpage was written by Julien Delange <julien AT gunnm DOT org> for Debian.

