.TH ED2K.AMULE 1
.SH NAME
ed2k \- binary used by aMule program.
.SH SYNOPSIS
.B ed2k.amule
.SH "DESCRIPTION"
.B ed2k
is a binary used by the aMule program. It is used to get ed2k link.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH AUTHOR
ed2k was written by the aMule team, see http://amule.sourceforge.net
This manpage was written by Julien Delange for Debian <julien AT gunnm DOT org>



