.TH ED2K 1
.SH NAME
ed2k \- wrapper pour aMule et xMule
.SH SYNOPSIS
.B ed2k
.SH "DESCRIPTION"
.B ed2k
est un wrapper utilisé pour passer les URL ed2k:// à ed2k.amule ou ed2k.xmule. Ce programme est spécifique à Debian.
.PP
Cette page de manuel a été écrite pour Debian, car le logiciel original n'en avait pas.

.SH "AUTEUR"
ed2k et cette page de manuel ont été écrit par Julien Delange <julien AT gunnm DOT org> pour Debian.


